# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


paginate: 4
paginate_path: '/blog/page:num/'
permalink: '/blog/:year/:month/:day/:title/'

title: '/home/hashb'
description: 'Blog about AI, Machine Learning and Robots.'
name: 'Chenna Kautilya'

baseurl: ''  # the subpath of your site, e.g. /blog
url: 'https://chenna.me'  # the base hostname & protocol for your site

twitter_username: 'kautilyach'
github_username:  'hashb'

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

gfm_quirks: paragraph_end

future: true
jailed: false

plugins: [jekyll-paginate,
          jekyll-sitemap]

remote_theme: hashb/california
incremental: false

port: 4040
