# Site settings

title: "Chenna Kautilya ~ /home/hashb"
title_body: '/home/hashb'
description: 'Chenna Kautilya | Makes Robots Move'
name: 'Chenna Kautilya''s home on the Internet'

baseurl: ''  # the subpath of your site, e.g. /blog
url: 'https://chenna.me'  # the base hostname & protocol for your site
repo_url: 'https://github.com/hashb/chenna.me'

timezone: UTC

paginate: 4
paginate_path: '/blog/page:num/'
permalink: '/blog/:year/:month/:day/:title/'

excerpt_separator: <!-- more -->

collections:
  projects:
    output: true
    permalink: '/work/:year/:month/:title/'

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

gfm_quirks: paragraph_end

future: true
jailed: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
  - jekyll-redirect-from

remote_theme: hashb/california
incremental: false

jekyll_compose:
  default_front_matter:
    posts:
      last_modified_at:
      tags:
      published: true

# TODO: Uncomment this when https://github.com/jekyll/jekyll-feed/pull/321 is merged
# feed:
#   tags:
#     except:
#       - "Captain's log"

author: 
  name: Chenna Kautilya
  rss: true
  mail: hi@chenna.me
  twitter: kautilyach
  github: hashb
  youtube: kautilyach
  linkedin: kautilyach

# Social
twitter_username: 'kautilyach'
github_username:  'hashb'
linkedin_username: 'kautilyach'

twitter:
  username: kautilyach

social:
  name: Chenna Kautilya
  links:
    - https://twitter.com/kautilyach
    - https://www.linkedin.com/in/kautilyach
    - https://github.com/hashb
    - https://keybase.io/hashb

port: 4000
