# Site settings

title: '/home/hashb'
description: 'Blog about AI, Machine Learning and Robots.'
name: 'Chenna Kautilya'

baseurl: ''  # the subpath of your site, e.g. /blog
url: 'https://chenna.me'  # the base hostname & protocol for your site

paginate: 4
paginate_path: '/blog/page:num/'
permalink: '/blog/:year/:month/:day/:title/'

excerpt_separator: <!-- more -->

collections:
  projects:
    output: true
    permalink: '/work/:year/:month/:title/'

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

gfm_quirks: paragraph_end

future: true
jailed: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

remote_theme: hashb/california
incremental: false

# Social
twitter_username: 'kautilyach'
github_username:  'hashb'
linkedin_username: 'kautilyachenna'

twitter:
  username: kautilyach

social:
  name: Chenna Kautilya
  links:
    - https://twitter.com/kautilyach
    - https://www.linkedin.com/in/kautilyachenna
    - https://github.com/hashb
    - https://keybase.io/hashb

port: 4040
