# Site settings

title: '/home/hashb'
description: 'Blog about AI, Machine Learning and Robots.'
name: 'Chenna Kautilya'

baseurl: ''  # the subpath of your site, e.g. /blog
url: 'https://chenna.me'  # the base hostname & protocol for your site

# Social
twitter_username: 'kautilyach'
github_username:  'hashb'
linkedin_username: 'kautilyachenna'

paginate: 4
paginate_path: '/blog/page:num/'
permalink: '/blog/:year/:month/:day/:title/'

collections:
  projects:
    output: true
    permalink: /work/:name

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

gfm_quirks: paragraph_end

future: true
jailed: false

plugins: [jekyll-paginate,
          jekyll-sitemap]

remote_theme: hashb/california
incremental: false

port: 4040
